codeServer:
  codeServer:
    image:
      repository: codercom/code-server
      tag: latest
  password: "CHANGEME"
  ports:
  - port: 80
    targetPort: 8080
  replicas: 1
  type: ClusterIP
pvc:
  codeServer:
    storageRequest: 5Gi
