apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-server.fullname" . }}-code-server
  labels:
  {{- include "code-server.labels" . | nindent 4 }}
stringData:
  password: {{ required "codeServer.password is required" .Values.codeServer.password
    | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "code-server.fullname" . }}-code-server
  labels:
  {{- include "code-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.codeServer.type }}
  selector:
    app: code-server
  {{- include "code-server.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.codeServer.ports | toYaml | nindent 2 -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "code-server.fullname" . }}-code-server
  labels:
  {{- include "code-server.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.codeServer.storageRequest | quote }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "code-server.fullname" . }}-code-server
  labels:
  {{- include "code-server.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kubernetes.example.com
    http:
      paths:
      - backend:
          service:
            name: '{{ include "code-server.fullname" . }}-code-server'
            port:
              number: 80
        path: /codeserver
        pathType: Prefix