apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "code-server.fullname" . }}-code-server
  labels:
    app: code-server
  {{- include "code-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.codeServer.replicas }}
  selector:
    matchLabels:
      app: code-server
    {{- include "code-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: code-server
      {{- include "code-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ include "code-server.fullname" . }}-code-server
        image: {{ .Values.codeServer.codeServer.image.repository }}:{{ .Values.codeServer.codeServer.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: Always
        name: code-server
        resources: {}
        volumeMounts:
        - mountPath: /home/coder
          name: coder
      volumes:
      - name: coder
        persistentVolumeClaim:
          claimName: {{ include "code-server.fullname" . }}-code-server