{{- if .Values.route.enabled -}}
{{- $fullName := include "code-server.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  to:
    kind: Service
    name: {{ include "code-server.name" . }}
  port:
    targetPort: {{ tpl .Values.route.targetPort . }}
{{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  {{- if .Values.route.tls.key }}
    key: |-
      {{- .Values.route.tls.key | nindent 6 }}
  {{- end }}
  {{- if .Values.route.tls.destinationCACertificate }}
    destinationCACertificate: |-
      {{- .Values.route.tls.destinationCACertificate | nindent 6 }}
  {{- end }}
  {{- if .Values.route.tls.caCertificate }}
    caCertificate: |-
      {{- .Values.route.tls.caCertificate | nindent 6 }}
  {{- end }}
  {{- if .Values.route.tls.certificate }}
    certificate: |-
      {{- .Values.route.tls.certificate | nindent 6 }}
  {{- end }}

{{- end }}
{{- end }}
