---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-server.fullname" . }}-code-server
  labels:
  {{- include "code-server.labels" . | nindent 4 }}
stringData:
  password: {{ required "codeServer.password is required" .Values.codeServer.password
    | quote }}
