---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "code-server.fullname" . }}-code-server
  labels:
  {{- include "code-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.codeServer.type }}
  selector:
    app: code-server
  {{- include "code-server.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.codeServer.ports | toYaml | nindent 2 -}}
